# Generated by Django 3.0.8 on 2020-10-26 09:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import django_currentuser.db.models.fields
import django_currentuser.middleware
import jsonfield.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_dict', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_path', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])])),
                ('owner', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegularExp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150)),
                ('subcategory', models.CharField(max_length=150)),
                ('expression', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SyntacticResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', jsonfield.fields.JSONField()),
                ('rule', jsonfield.fields.JSONField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.Document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SemanticResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', jsonfield.fields.JSONField()),
                ('rule', jsonfield.fields.JSONField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.Document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SemanticData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', jsonfield.fields.JSONField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('phone_is_verified', models.BooleanField(default=False)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('postalCode', models.IntegerField(blank=True, null=True)),
                ('company_name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_column', models.CharField(max_length=200)),
                ('second_column', models.CharField(max_length=200)),
                ('relationship', models.CharField(max_length=100)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.Document')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisTrace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('running', 'Running'), ('finished', 'Finished'), ('failed', 'Failed')], default='running', max_length=100)),
                ('analysis_type', models.CharField(choices=[('basic', 'Basic-Analysis'), ('string', 'String-Analysis'), ('number', 'Number-Analysis'), ('date', 'Date-Analysis')], max_length=100)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.Document')),
            ],
        ),
    ]
